tap "homebrew/cask", "https://mirrors.ustc.edu.cn/homebrew-cask.git"
tap "homebrew/core", "https://mirrors.ustc.edu.cn/homebrew-core.git"
brew "cmake"
brew "dos2unix"
brew "gcc"
brew "go"
brew "jq"
brew "neovim"
brew "node"
brew "poetry"
brew "prettier"
brew "python@3.10"
brew "ripgrep"
brew "telnet"
brew "tmux"
brew "tree"
brew "v2ray"
brew "watch"
brew "wget"
brew "wireguard-tools"
cask "cloudflare-warp"
cask "font-meslo-lg-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "keepassxc"
cask "obsidian"
cask "qqmusic"
cask "raycast"
cask "sublime-text"
# cask "trae"
cask "visual-studio-code"
cask "wechat"
# cask "wezterm"
