brew "go"
brew "jq"
brew "neovim"
brew "node@22"
brew "poetry"
brew "prettier"
brew "python@3.12"
brew "ripgrep"
brew "telnet"
brew "tmux"
brew "tree"
brew "v2ray"
brew "wget"
brew "wireguard-tools"
# cask "adrive"
# cask "cloudflare-warp"
cask "font-meslo-lg-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "keepassxc"
cask "mailmaster"
cask "obsidian"
# cask "openvpn-connect"
cask "qqmusic"
cask "raycast"
cask "sublime-text"
# cask "trae"
# cask "visual-studio-code"
cask "wechat"
# cask "wezterm"
