model = "gpt-5.5"
model_reasoning_effort = "medium"

[projects."~/Projects/automation"]
trust_level = "trusted"

[projects."~/Projects/devops-marketplace"]
trust_level = "trusted"

[projects."~/Projects/dockerfiles"]
trust_level = "trusted"

[projects."~/Projects/environment"]
trust_level = "trusted"

[projects."~/Projects/helm-charts"]
trust_level = "trusted"

[projects."~/Projects/optimus"]
trust_level = "trusted"

[projects."~/Projects/terraform"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[plugins."superpowers@openai-curated"]
enabled = true
